title: Julie McDonald-Gillespie
logo: "/images/Profile.jpg?raw=true"
description: > 
  My name is Julie McDonald-Gillespie. I am a Environmental Scientist with Burns & McDonnell.
  <br><br>
  I have an A.S. in Environmental Science, a B.S. in Biogosciences, and am working to complete my M.S. in Geospatial Technology. 
  I've worked with ArcGIS Pro, PostGIS, Python, Bash, R Studio, and Jupyter Notebook.
  <br><br>
  <a href="www.linkedin.com/in/julie-mcdonald-gillespie-3895b1199</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
